-- =============================================================================
-- USE CASE DESCRIPTIONS TABLE (DBSQL / Delta Lake)
-- =============================================================================
-- Stores versioned use case descriptions for industries and their use cases.
-- Latest version = MAX(version) per (industry, use_case)
-- Variables: ${catalog}.${schema} - replaced at runtime
-- =============================================================================

CREATE TABLE IF NOT EXISTS ${catalog}.${schema}.usecase_descriptions (
    config_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    industry STRING NOT NULL,
    industry_label STRING NOT NULL,
    use_case STRING NOT NULL,
    use_case_label STRING NOT NULL,
    prompt_template STRING NOT NULL,
    version INT NOT NULL DEFAULT 1,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    inserted_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by STRING
) USING DELTA
TBLPROPERTIES ('delta.feature.allowColumnDefaults' = 'supported');
