-- =============================================================================
-- SECTION INPUT PROMPTS TABLE (DBSQL / Delta Lake)
-- =============================================================================
-- Stores versioned section input prompts for LLM prompt generation.
-- Latest version = MAX(version) per section_tag
-- Variables: ${catalog}.${schema} - replaced at runtime
-- =============================================================================

CREATE TABLE IF NOT EXISTS ${catalog}.${schema}.section_input_prompts (
    input_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    section_tag STRING NOT NULL,
    section_title STRING,
    section_description STRING,
    input_template STRING NOT NULL,
    system_prompt STRING NOT NULL,
    order_number INT,
    how_to_apply STRING,
    expected_output STRING,
    how_to_apply_images STRING DEFAULT '[]',
    expected_output_images STRING DEFAULT '[]',
    bypass_llm BOOLEAN NOT NULL DEFAULT FALSE,
    step_enabled BOOLEAN NOT NULL DEFAULT TRUE,
    version INT NOT NULL DEFAULT 1,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    inserted_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by STRING
) USING DELTA
TBLPROPERTIES ('delta.feature.allowColumnDefaults' = 'supported');
