-- =============================================================================
-- WORKSHOP PARAMETERS TABLE (DBSQL / Delta Lake)
-- =============================================================================
-- Stores configurable key-value parameters that are available to all workflow
-- steps and section input prompts. These parameters are replaced in templates
-- using {param_key} syntax (e.g., {workspace_url}, {default_warehouse}).
--
-- Variables: ${catalog}.${schema} - replaced at runtime
-- =============================================================================

CREATE TABLE IF NOT EXISTS ${catalog}.${schema}.workshop_parameters (
    param_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    param_key STRING NOT NULL,
    param_label STRING NOT NULL,
    param_value STRING NOT NULL,
    param_description STRING,
    param_type STRING NOT NULL DEFAULT 'text',
    display_order INT NOT NULL DEFAULT 0,
    is_required BOOLEAN NOT NULL DEFAULT FALSE,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    allow_session_override BOOLEAN NOT NULL DEFAULT TRUE,
    inserted_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by STRING
) USING DELTA
TBLPROPERTIES ('delta.feature.allowColumnDefaults' = 'supported');
