-- =============================================================================
-- SAVED USE CASE DESCRIPTIONS TABLE (DBSQL / Delta Lake)
-- =============================================================================
-- Stores user-generated use case descriptions from the Build Your Use Case
-- [Beta] feature. Community library -- all users can view and edit.
-- Variables: ${catalog}.${schema} - replaced at runtime
-- =============================================================================

CREATE TABLE IF NOT EXISTS ${catalog}.${schema}.saved_usecase_descriptions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_by STRING NOT NULL,
    display_name STRING,
    updated_by STRING,
    industry STRING,
    use_case_name STRING,
    description STRING NOT NULL,
    version INT DEFAULT 1,
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
) USING DELTA
TBLPROPERTIES ('delta.feature.allowColumnDefaults' = 'supported');
