#!/usr/bin/env python3
"""T5 R1 — emit the frozen ``step_map`` CTE used by the gates-backfill runbook.

READ-ONLY. This script connects to NOTHING (no Lakebase, no Databricks, no SQL
execution). It reads the generated workshop manifest's GLOBAL ``ALL_STEPS``
``step_number -> sectionTag`` map (``manifest.step_number_to_tag()``) and prints
a deterministic PostgreSQL ``WITH step_map(step_number, tag) AS (VALUES ...)``
common table expression to stdout.

That CTE is the single source of truth the runbook's backfill / rollback UPDATEs
reuse to translate the legacy numeric ``completed_steps`` / ``skipped_steps``
columns into the gate ``sectionTag`` sets the read path (T5 PR1) trusts. It is
the SQL mirror of the frontend ``stepNumbersToGates`` dual-write
(``src/constants/workflowSections.ts``) and of ``completion_keying`` on the
backend — all three key off the SAME manifest map, so global-number authority
stays singular.

Ordering is by ascending ``step_number`` so the emitted text is byte-stable
across runs (a non-deterministic order would make the three-way map-pin test and
any ``diff`` against the runbook flap). The map is sparse where steps were retired
(e.g. there is no global 70), which is expected: the VALUES list reflects exactly
the live manifest.

Usage::

    python scripts/r1_emit_map_sql.py            # print the CTE
    python scripts/r1_emit_map_sql.py --manifest /path/to/manifest.json

The three-way pin test (``tests/workshop/test_r1_backfill_runbook.py``) asserts
that ``manifest.step_number_to_tag()`` == the VALUES parsed out of THIS script's
output == the VALUES parsed out of the runbook .md. Tampering any one of the
three makes that test fail.
"""

from __future__ import annotations

import argparse
import pathlib
import sys

# Make the repo importable when run as a plain script (scripts/ is not a package).
_REPO_ROOT = pathlib.Path(__file__).resolve().parents[1]
if str(_REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(_REPO_ROOT))

from src.backend.workshop import manifest  # noqa: E402  (after sys.path shim)

# Marker lines so downstream parsers (tests, the runbook) can locate the CTE
# unambiguously inside a larger document without guessing at surrounding prose.
CTE_BEGIN = "-- >>> R1 STEP_MAP CTE (generated by scripts/r1_emit_map_sql.py) >>>"
CTE_END = "-- <<< R1 STEP_MAP CTE <<<"


def render_cte(number_to_tag: dict[int, str]) -> str:
    """Render the frozen ``step_map`` CTE from a step-number -> tag map.

    Rows are emitted in ascending ``step_number`` order; the final row carries no
    trailing comma so the VALUES list is valid PostgreSQL."""

    ordered = sorted(number_to_tag.items(), key=lambda kv: kv[0])
    if not ordered:
        raise SystemExit("refusing to emit an empty step_map (manifest map is empty)")

    rows = [f"    ({number}, '{tag}')" for number, tag in ordered]
    body = ",\n".join(rows)
    return (
        f"{CTE_BEGIN}\n"
        "WITH step_map(step_number, tag) AS (\n"
        "  VALUES\n"
        f"{body}\n"
        ")\n"
        f"{CTE_END}"
    )


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--manifest",
        default=None,
        help="Optional path to a manifest.json (defaults to the packaged manifest).",
    )
    args = parser.parse_args(argv)

    number_to_tag = manifest.step_number_to_tag(args.manifest)
    print(render_cte(number_to_tag))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
