#!/usr/bin/env python3
"""
vibe2value CLI - Installer and deployment tool for Vibe Coding Workshop App.

Commands:
    install     Interactive first-time setup and deploy
    configure   Regenerate config files from templates (no deploy)
    deploy      Deploy code changes (default: code-only)
    doctor      Validate prerequisites and configuration
    uninstall   Tear down all provisioned resources
"""

import argparse
import json
import os
import shutil
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent.parent
CONFIG_PATH = PROJECT_ROOT / "user-config.yaml"
TEMPLATES = {
    "app.yaml": PROJECT_ROOT / "app.yaml.template",
    "databricks.yml": PROJECT_ROOT / "databricks.yml.template",
    "seed_sql": PROJECT_ROOT / "db" / "lakebase" / "dml_seed" / "03_seed_workshop_parameters.sql.template",
}

GREEN = "\033[0;32m"
YELLOW = "\033[1;33m"
RED = "\033[0;31m"
BLUE = "\033[0;34m"
CYAN = "\033[0;36m"
BOLD = "\033[1m"
NC = "\033[0m"


def info(msg):
    print(f"{CYAN}> {msg}{NC}")


def success(msg):
    print(f"{GREEN}  [ok] {msg}{NC}")


def warn(msg):
    print(f"{YELLOW}  [warn] {msg}{NC}")


def error(msg):
    print(f"{RED}  [error] {msg}{NC}")


def header(msg):
    print(f"\n{BOLD}{BLUE}{'=' * 60}{NC}")
    print(f"{BOLD}{BLUE}  {msg}{NC}")
    print(f"{BOLD}{BLUE}{'=' * 60}{NC}\n")


def step(current: int, total: int, msg: str):
    bar_width = 30
    filled = int(bar_width * current / total)
    bar = f"{'█' * filled}{'░' * (bar_width - filled)}"
    print(f"\n{BOLD}{CYAN}  [{current}/{total}] {bar} {msg}{NC}\n")


# ---------------------------------------------------------------------------
# YAML helpers (no pyyaml dependency -- simple key: value parsing)
# ---------------------------------------------------------------------------

def load_config() -> dict:
    """Load user-config.yaml into a nested dict."""
    if not CONFIG_PATH.exists():
        return {}
    config = {}
    current_section = None
    with open(CONFIG_PATH) as f:
        for line in f:
            stripped = line.strip()
            if not stripped or stripped.startswith("#"):
                continue
            if stripped.endswith(":") and not stripped.startswith("-"):
                current_section = stripped[:-1].strip()
                config[current_section] = {}
            elif ":" in stripped and current_section is not None:
                key, _, value = stripped.partition(":")
                key = key.strip()
                value = value.strip().strip('"').strip("'")
                if value == "[]":
                    value = []
                config[current_section][key] = value
    return config


def save_config(config: dict):
    """Write config dict back to user-config.yaml."""
    lines = [
        "# =============================================================================",
        "# Vibe Coding Workshop - User Configuration",
        "# =============================================================================",
        "# Generated by vibe2value. Edit values here, then run:",
        "#   ./vibe2value configure    (regenerate config files)",
        "#   ./vibe2value deploy       (push code changes)",
        "#   ./vibe2value deploy --full (full infrastructure deploy)",
        "# =============================================================================",
        "",
    ]
    for section, values in config.items():
        lines.append(f"{section}:")
        if isinstance(values, dict):
            for k, v in values.items():
                if isinstance(v, list):
                    lines.append(f'  {k}: []')
                else:
                    lines.append(f'  {k}: "{v}"')
        lines.append("")
    with open(CONFIG_PATH, "w") as f:
        f.write("\n".join(lines) + "\n")


def get_placeholder_map(config: dict) -> dict:
    """Map __PLACEHOLDER__ tokens to config values."""
    ws = config.get("workspace", {})
    lb = config.get("lakebase", {})
    app = config.get("app", {})
    user = config.get("user", {})
    return {
        "__WORKSPACE_HOST__": ws.get("host", ""),
        "__WORKSPACE_URL__": ws.get("host", "").rstrip("/") + "/",
        "__WORKSPACE_ORG_ID__": ws.get("org_id", ""),
        "__LAKEBASE_INSTANCE_NAME__": lb.get("instance_name", ""),
        "__LAKEBASE_CATALOG__": lb.get("catalog", ""),
        "__LAKEBASE_SCHEMA__": lb.get("schema", ""),
        "__LAKEBASE_HOST__": "",  # discovered at deploy time
        "__LAKEBASE_USER__": user.get("email", ""),
        "__LAKEBASE_UC_CATALOG__": lb.get("uc_catalog", lb.get("catalog", "") + "_lakebase"),
        "__APP_NAME__": app.get("name", ""),
        "__SERVING_ENDPOINT__": app.get("serving_endpoint", "databricks-claude-sonnet-4-5"),
        "__DEFAULT_WAREHOUSE__": lb.get("warehouse", ""),
    }


# ---------------------------------------------------------------------------
# Template rendering
# ---------------------------------------------------------------------------

def render_template(template_path: Path, output_path: Path, placeholders: dict,
                    flags: dict | None = None):
    """Replace __PLACEHOLDER__ tokens and process conditional blocks.

    Conditional blocks use the syntax:
        # __IF_FLAG_NAME__
        ... content ...
        # __ENDIF_FLAG_NAME__

    If flags["FLAG_NAME"] is truthy, the content (and markers) are kept.
    If falsy, the entire block including markers is removed.
    """
    content = template_path.read_text()
    if flags:
        import re as _re
        for flag_name, enabled in flags.items():
            pattern = (
                rf"^[^\S\n]*#\s*__IF_{flag_name}__\s*\n"
                rf"(.*?)"
                rf"^[^\S\n]*#\s*__ENDIF_{flag_name}__\s*\n"
            )
            if enabled:
                content = _re.sub(pattern, r"\1", content, flags=_re.MULTILINE | _re.DOTALL)
            else:
                content = _re.sub(pattern, "", content, flags=_re.MULTILINE | _re.DOTALL)
    for token, value in placeholders.items():
        content = content.replace(token, value)
    output_path.write_text(content)
    return output_path


# ---------------------------------------------------------------------------
# Prerequisites
# ---------------------------------------------------------------------------

def check_prerequisites() -> bool:
    """Check that required tools are installed."""
    all_ok = True
    checks = [
        ("python3", "Python 3"),
        ("node", "Node.js"),
        ("npm", "npm"),
        ("databricks", "Databricks CLI"),
    ]
    for cmd, label in checks:
        if shutil.which(cmd):
            version = ""
            try:
                result = subprocess.run([cmd, "--version"], capture_output=True, text=True, timeout=10)
                version = result.stdout.strip().split("\n")[0] if result.stdout else ""
            except Exception:
                pass
            success(f"{label}: {version}")
        else:
            error(f"{label}: NOT FOUND")
            all_ok = False
    return all_ok


def check_auth(profile: str = "") -> dict:
    """Check Databricks CLI authentication, return user info."""
    cmd = ["databricks", "current-user", "me", "--output", "json"]
    if profile:
        cmd.extend(["--profile", profile])
    try:
        result = subprocess.run(cmd, capture_output=True, text=True, timeout=30)
        if result.returncode == 0:
            user_info = json.loads(result.stdout)
            return user_info
    except Exception:
        pass
    return {}


def discover_profile(host: str) -> str:
    """Find the Databricks CLI profile that matches a workspace host URL."""
    try:
        result = subprocess.run(
            ["databricks", "auth", "profiles", "--output", "json"],
            capture_output=True, text=True, timeout=15,
        )
        if result.returncode == 0:
            data = json.loads(result.stdout)
            profiles = data.get("profiles", data) if isinstance(data, dict) else data
            host_clean = host.rstrip("/").lower()
            for p in profiles:
                p_host = (p.get("host", "") or "").rstrip("/").lower()
                if p_host == host_clean:
                    return p.get("name", "")
    except Exception:
        pass
    return ""



# ---------------------------------------------------------------------------
# Commands
# ---------------------------------------------------------------------------

def _run_deploy(phase_flags: list, config: dict, label: str, step_num: int,
                total: int) -> int:
    """Run deploy.sh with the given flags. Returns exit code."""
    deploy_sh = str(PROJECT_ROOT / "scripts" / "deploy.sh")
    target = config.get("_metadata", {}).get("target", "user")
    profile = config.get("workspace", {}).get("profile", "")
    cmd = [deploy_sh, "--target", target] + phase_flags
    if profile:
        cmd.extend(["--profile", profile])
    result = subprocess.run(cmd, cwd=PROJECT_ROOT)
    if result.returncode != 0:
        print()
        header("INSTALL FAILED")
        error(f"Failed at step {step_num}/{total}: {label}")
        print(f"  Your configuration is saved in {CYAN}user-config.yaml{NC}.")
        print(f"  Fix the issue above, then run {CYAN}./vibe2value deploy --full{NC} to retry.")
        print()
        sys.exit(result.returncode)
    return result.returncode


def cmd_install(args):
    """Interactive first-time setup and deploy."""
    TOTAL = 7
    header("VIBE2VALUE INSTALL")

    # ── Step 1: Prerequisites ─────────────────────────────────────────
    step(1, TOTAL, "Checking prerequisites")
    if not check_prerequisites():
        error("Missing prerequisites. Please install the tools above and retry.")
        sys.exit(1)

    # ── Step 2: Workspace URL ─────────────────────────────────────────
    step(2, TOTAL, "Workspace connection")
    existing_config = load_config()
    default_host = existing_config.get("workspace", {}).get("host", "")

    if default_host:
        host = input(f"  Databricks workspace URL [{default_host}]: ").strip() or default_host
    else:
        host = input("  Databricks workspace URL: ").strip()

    if not host:
        error("Workspace URL is required.")
        sys.exit(1)
    host = host.rstrip("/")
    if not host.startswith("https://"):
        host = "https://" + host

    # ── Step 3: Authenticate ──────────────────────────────────────────
    step(3, TOTAL, "Authenticating")
    profile = existing_config.get("workspace", {}).get("profile", "")
    user_info = check_auth(profile) if profile else {}
    if not user_info:
        info("Opening browser for authentication...")
        auth_cmd = ["databricks", "auth", "login", "--host", host]
        subprocess.run(auth_cmd)
        profile = discover_profile(host)
        user_info = check_auth(profile)

    if not user_info:
        error("Authentication failed. Run 'databricks auth login --host <URL>' manually.")
        sys.exit(1)

    email = user_info.get("userName", "")
    success(f"Authenticated as: {email}")
    if profile:
        success(f"Using CLI profile: {profile}")

    # ── Step 4: Configure resources ───────────────────────────────────
    step(4, TOTAL, "Configure resources")
    defaults = {
        "app_name": existing_config.get("app", {}).get("name", "vibe-coding-workshop-app"),
        "instance_name": existing_config.get("lakebase", {}).get("instance_name", "vibe-coding-workshop-lakebase"),
        "catalog": existing_config.get("lakebase", {}).get("catalog", "vibe_coding_workshop_catalog"),
        "schema": existing_config.get("lakebase", {}).get("schema", "vibe_coding_workshop"),
        "endpoint": existing_config.get("app", {}).get("serving_endpoint", "databricks-claude-sonnet-4-5"),
        "warehouse": existing_config.get("lakebase", {}).get("warehouse", ""),
    }

    app_name = input(f"  App name [{defaults['app_name']}]: ").strip() or defaults["app_name"]
    instance_name = input(f"  Lakebase instance [{defaults['instance_name']}]: ").strip() or defaults["instance_name"]
    catalog = input(f"  Catalog [{defaults['catalog']}]: ").strip() or defaults["catalog"]
    create_catalog_input = input(
        "  Register Lakebase as UC catalog? (needs CREATE CATALOG permission) [y/N]: "
    ).strip().lower()
    create_catalog = create_catalog_input in ("y", "yes")
    endpoint = input(f"  Model endpoint [{defaults['endpoint']}]: ").strip() or defaults["endpoint"]

    # ── Step 5: Save configuration ────────────────────────────────────
    step(5, TOTAL, "Saving configuration & generating files")
    target = existing_config.get("_metadata", {}).get("target", "user")
    config = {
        "workspace": {
            "host": host,
            "profile": profile,
        },
        "lakebase": {
            "instance_name": instance_name,
            "catalog": catalog,
            "create_catalog": "true" if create_catalog else "false",
            "schema": defaults["schema"],
            "database": "databricks_postgres",
            "warehouse": defaults["warehouse"],
            "uc_catalog": catalog.replace("_catalog", "_lakebase") if "_catalog" in catalog else catalog + "_lakebase",
        },
        "app": {
            "name": app_name,
            "serving_endpoint": endpoint,
        },
        "user": {
            "email": email,
        },
        "_metadata": {
            "installed_at": datetime.now(timezone.utc).isoformat(),
            "installer_version": "1.0.0",
            "target": target,
            "created_resources": [],
        },
    }

    save_config(config)
    success(f"Saved {CONFIG_PATH.name}")
    cmd_configure(args, config=config)

    # ── Step 6: Build frontend ────────────────────────────────────────
    step(6, TOTAL, "Building frontend")
    info("Running npm install...")
    npm_result = subprocess.run(["npm", "install"], cwd=PROJECT_ROOT, capture_output=True, text=True)
    if npm_result.returncode != 0:
        warn("npm install had issues, continuing...")
    info("Running npm build...")
    build_result = subprocess.run(["npm", "run", "build"], cwd=PROJECT_ROOT)
    if build_result.returncode != 0:
        error("Frontend build failed")
        sys.exit(1)
    success("Frontend built")

    # ── Step 7: Full deploy ─────────────────────────────────────────
    step(7, TOTAL, "Deploying to Databricks")
    info("Running full deployment (infrastructure, code, permissions, tables)...")
    info("This may take several minutes on first deploy...")
    _run_deploy([], config, "Full deploy", 7, TOTAL)
    success("Deployment complete")

    # ── Done ──────────────────────────────────────────────────────────
    print()
    header("INSTALL COMPLETE")
    step(TOTAL, TOTAL, "Done!")
    print(f"  {GREEN}All {TOTAL} steps completed successfully.{NC}")
    print()
    print(f"  {BOLD}Next time you make changes:{NC}")
    print(f"    {CYAN}./vibe2value deploy{NC}        Code-only deploy")
    print(f"    {CYAN}./vibe2value deploy --full{NC}  Full infrastructure deploy")
    print(f"    {CYAN}./vibe2value doctor{NC}         Validate your setup")
    print()


def cmd_configure(args, config=None):
    """Regenerate config files from templates."""
    if config is None:
        config = load_config()
    if not config:
        error("No user-config.yaml found. Run './vibe2value install' first.")
        sys.exit(1)

    info("Rendering config files from templates...")
    placeholders = get_placeholder_map(config)
    lb = config.get("lakebase", {})
    flags = {
        "CREATE_CATALOG": lb.get("create_catalog", "true").lower() == "true",
    }

    rendered = []
    for name, tmpl_path in TEMPLATES.items():
        if not tmpl_path.exists():
            warn(f"Template not found: {tmpl_path.name}")
            continue
        if name == "seed_sql":
            out_path = tmpl_path.parent / tmpl_path.name.replace(".template", "")
        else:
            out_path = PROJECT_ROOT / name
        render_template(tmpl_path, out_path, placeholders, flags=flags)
        rendered.append(out_path.relative_to(PROJECT_ROOT))

    for r in rendered:
        success(f"Generated {r}")
    print()


def cmd_deploy(args):
    """Deploy code changes. Default is code-only."""
    config = load_config()

    deploy_cmd = [str(PROJECT_ROOT / "scripts" / "deploy.sh")]

    # Determine target
    if config:
        ws = config.get("workspace", {})
        profile = ws.get("profile", "")

        meta = config.get("_metadata", {})
        target = getattr(args, "target", "") or meta.get("target", "") or "production"
        deploy_cmd.extend(["--target", target])
        if profile:
            deploy_cmd.extend(["--profile", profile])
    else:
        warn("No user-config.yaml found. Using deploy.sh defaults.")

    # Deploy mode
    if getattr(args, "full", False):
        pass  # Full deploy (no extra flags)
    elif getattr(args, "tables", False):
        deploy_cmd.append("--tables-only")
    elif getattr(args, "watch", False):
        deploy_cmd.append("--watch")
    else:
        deploy_cmd.append("--code-only")
        if getattr(args, "skip_build", False):
            deploy_cmd.append("--skip-build")

    info(f"Running: {' '.join(deploy_cmd)}")
    print()
    result = subprocess.run(deploy_cmd, cwd=PROJECT_ROOT)
    sys.exit(result.returncode)


def cmd_doctor(args):
    """Validate prerequisites and configuration."""
    header("VIBE2VALUE DOCTOR")
    all_ok = True

    # Prerequisites
    info("Checking prerequisites...")
    if not check_prerequisites():
        all_ok = False
    print()

    # Config file
    info("Checking configuration...")
    if CONFIG_PATH.exists():
        config = load_config()
        success(f"user-config.yaml exists")
        ws_host = config.get("workspace", {}).get("host", "")
        app_name = config.get("app", {}).get("name", "")
        if ws_host:
            success(f"Workspace: {ws_host}")
        else:
            warn("Workspace host not set")
            all_ok = False
        if app_name:
            success(f"App: {app_name}")
        else:
            warn("App name not set")
            all_ok = False
    else:
        warn("user-config.yaml not found (run './vibe2value install')")
        all_ok = False
    print()

    # Generated files
    info("Checking generated files...")
    for name in ["databricks.yml", "app.yaml"]:
        p = PROJECT_ROOT / name
        if p.exists():
            success(f"{name} exists")
        else:
            warn(f"{name} missing")
            all_ok = False
    print()

    # Databricks CLI auth
    info("Checking Databricks CLI authentication...")
    profile = ""
    if CONFIG_PATH.exists():
        config = load_config()
        profile = config.get("workspace", {}).get("profile", "")
    user_info = check_auth(profile)
    if user_info:
        success(f"Authenticated as: {user_info.get('userName', 'unknown')}")
    else:
        error("Not authenticated. Run 'databricks auth login --host <URL>'")
        all_ok = False
    print()

    if all_ok:
        print(f"{GREEN}{BOLD}All checks passed!{NC}")
    else:
        print(f"{YELLOW}{BOLD}Some checks failed. See warnings above.{NC}")

    return 0 if all_ok else 1


def cmd_uninstall(args):
    """Tear down all provisioned resources."""
    header("VIBE2VALUE UNINSTALL")

    config = load_config()
    if not config:
        error("No user-config.yaml found. Nothing to uninstall.")
        sys.exit(1)

    ws = config.get("workspace", {})
    app_cfg = config.get("app", {})
    lb = config.get("lakebase", {})
    meta = config.get("_metadata", {})

    print(f"  Workspace:  {ws.get('host', 'unknown')}")
    print(f"  App:        {app_cfg.get('name', 'unknown')}")
    print(f"  Instance:   {lb.get('instance_name', 'unknown')}")
    print(f"  Catalog:    {lb.get('catalog', 'unknown')}")
    print(f"  Schema:     {lb.get('schema', 'unknown')}")
    print()

    if getattr(args, "dry_run", False):
        info("DRY RUN: Would destroy the resources above. No changes made.")
        return

    if not getattr(args, "force", False):
        confirmation = input(f"  {RED}Type 'UNINSTALL' to confirm: {NC}")
        if confirmation != "UNINSTALL":
            print("  Aborted.")
            sys.exit(0)
    print()

    profile_flag = ["--profile", ws["profile"]] if ws.get("profile") else []

    # Step 1: Drop tables
    if not getattr(args, "keep_data", False):
        info("Step 1: Dropping Lakebase tables...")
        drop_cmd = [str(PROJECT_ROOT / "scripts" / "setup-lakebase.sh"), "--drop"]
        subprocess.run(drop_cmd, cwd=PROJECT_ROOT, env={**os.environ, "DATABRICKS_HOST": ws.get("host", "")})
    else:
        info("Step 1: Skipping table drop (--keep-data)")

    # Step 2: Delete app
    info("Step 2: Deleting Databricks App...")
    app_name = app_cfg.get("name", "")
    if app_name:
        del_cmd = ["databricks", "apps", "delete", app_name] + profile_flag
        subprocess.run(del_cmd, capture_output=True)
        success(f"Deleted app: {app_name}")

    # Step 3: Destroy bundle
    info("Step 3: Destroying DAB bundle...")
    target = meta.get("target", "production")
    destroy_cmd = ["databricks", "bundle", "destroy", "-t", target, "--auto-approve"] + profile_flag
    subprocess.run(destroy_cmd, cwd=PROJECT_ROOT, capture_output=True)
    success("Bundle destroyed")

    # Step 4: Clean local files
    info("Step 4: Cleaning local generated files...")
    for f in [CONFIG_PATH]:
        if f.exists():
            f.unlink()
            success(f"Removed {f.name}")

    print()
    header("UNINSTALL COMPLETE")


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main():
    parser = argparse.ArgumentParser(
        prog="vibe2value",
        description="Installer and deployment tool for Vibe Coding Workshop App",
    )
    subparsers = parser.add_subparsers(dest="command", help="Available commands")

    # install
    p_install = subparsers.add_parser("install", help="Interactive first-time setup and deploy")
    p_install.add_argument("--target", "-t", default="", help="Deploy target")

    # configure
    subparsers.add_parser("configure", help="Regenerate config files from templates")

    # deploy
    p_deploy = subparsers.add_parser("deploy", help="Deploy code changes")
    p_deploy.add_argument("--full", action="store_true", help="Full infrastructure deploy")
    p_deploy.add_argument("--watch", "-w", action="store_true", help="Continuous sync mode")
    p_deploy.add_argument("--tables", action="store_true", help="Reseed database only")
    p_deploy.add_argument("--skip-build", action="store_true", help="Skip frontend build")
    p_deploy.add_argument("--target", "-t", default="", help="Deploy target")

    # doctor
    subparsers.add_parser("doctor", help="Validate prerequisites and configuration")

    # uninstall
    p_uninstall = subparsers.add_parser("uninstall", help="Tear down all provisioned resources")
    p_uninstall.add_argument("--force", action="store_true", help="Skip confirmation")
    p_uninstall.add_argument("--dry-run", action="store_true", help="Show what would be deleted")
    p_uninstall.add_argument("--keep-data", action="store_true", help="Preserve Lakebase tables")

    args = parser.parse_args()

    if not args.command:
        parser.print_help()
        sys.exit(0)

    commands = {
        "install": cmd_install,
        "configure": cmd_configure,
        "deploy": cmd_deploy,
        "doctor": cmd_doctor,
        "uninstall": cmd_uninstall,
    }

    sys.exit(commands[args.command](args) or 0)


if __name__ == "__main__":
    main()
